### ISSUE TITLE
Can't close WIndow

### ISSUE THREAD

**Issue by rodude123** [MartijnVogelaar/krunner-spotify#26]
I can download it fine from the KDE Get new plugins place. I can type in KRunner to Play something, it asks me to login which when I click it loads up firefox, I log in but afterwards I cannot click the close window button. It does absolutely nothing. Then afterwards it comes up saying Invalid command Now I cannot log in again

**Comment by MartijnVogelaar** [comment]
Hi,

It seems that you have two problems:

- Not being able to close the window in the browser.
- Not being able to use the command through KRunner.

Regarding the first problem that you are unable to click the button to close the page, this is a problem in the used python library spotipy. I've opened an issue there, see: https://github.com/plamere/spotipy/issues/658.
Even though you cannot close the window using the button you can close the window yourself, not being able to close should not affect the krunner plugin at all.
What is the command you are trying to execute in KRunner? Could you try something like:

> Play song Billie Jean

It should show 5 results which you can select.

**Comment by rodude123** [comment]
I run that command and it gives me 5 results but they do nothing doesn't change the song at all

**Comment by MartijnVogelaar** [comment]
Do you have a premium Spotify account? The free version of Spotify does not allow you to control the song currently playing.

If you do have a Premium Spotify account, try the following:

> Navigate to the folder where you installed Spotify
> Execute: pkill python3
> Execute the debug.sh file by: ./debug.sh or sh debug.sh

Try to use the command again and look at possible output in the terminal where you executed the debug.sh file.

**Comment by MartijnVogelaar** [comment]
Ill be closing this issue for now as no reply has been given.
