### ISSUE TITLE
It just  doesnt work

### ISSUE THREAD

**Issue by pakosaan** [MartijnVogelaar/krunner-spotify#30]
I installed it but it doesnt launch nor shows anything related to this plugin. it is just like i never installed in the beginning.
No nothing . No command triggers it

**Comment by boehs** [comment]
It might have failed to install `spotipy`. Could you pip install it and try again?

**Comment by micimize** [comment]
Works fine for me but the install script doesn't install `spotipy` on its own

**Comment by MartijnVogelaar** [comment]
It is indeed most likely that you haven't installed all dependencies. The install script does not install dependencies on its own.
